name: Build
on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Build version'
                required: true
                type: string
                default: '5.15.2'
            configure-args:
                description: 'Build args'
                required: true
                type: string
            modules:
                description: 'Build modules'
                required: true
                type: string
                default: 'qtbase'
            arch:
                description: 'Build arch'
                type: choice
                options:
                  - x86
                  - x64
                required: true
jobs:
    build:
        name: Build
        runs-on: windows-2019

        steps:
            - name: Set up Visual Studio shell on Windows
              uses: egor-tensin/vs-shell@v2
              with:
                  arch: ${{ inputs.arch }}
            
            - name: Setup Environment
              working-directory: "C:/"
              shell: pwsh
              run: |
                mkdir C:/qt-source
                choco install -y jom sed
            
            - name: Download Qt
              working-directory: "C:/"
              shell: pwsh
              run: | 
                git clone https://github.com/qt/qt5.git C:/qt-source
                cd qt-source
                git checkout v${{ inputs.version }}
                perl init-repository --module-subset=${{ inputs.modules }}
                sed -i s/-MD/-MT/g qt-base/mkspecs/common/msvc-desktop.conf

            - name: Build
              working-directory: "C:/qt-source"
              shell: pwsh
              run: |
                mkdir build
                cd build
                ../configure -release -opensource -confirm-license -platform win32-msvc ${{ inputs.configure-args }} -prefix "C:\qt-static"
                jom
                jom install

            - name: Package output files
              working-directory: "D:/"
              shell: pwsh
              run: |
                7z a -t7z qt-${{inputs.version}}-${{inputs.arch}}-static.7z "C:\qt-static\*"

            - uses: actions/upload-artifact@v3
              with:
                  path: "D:/qt-${{inputs.version}}-${{inputs.arch}}-static.7z"